#metaG_accession: PRJNA766694
#metaG_ena_table: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/input/ENA_tables/PRJNA766694_metaG_wenv.txt

#inputDIR: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/input
#outputDIR: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/output

#scratch: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/scratch
#adapters: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/input/adapters/illumina-adapters.fa
#metaG_sample_list: /home/etucker5/miniconda3/envs/S-niv-MAGs/data/input/SampleList_ForAssembly_metaG.txt

#megahit_other: --continue --k-list 29,39,59,79,99,119
#megahit_cpu: 80
#megahit_min_contig: 1000
#megahit_mem: 0.95
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-secon: 10
local-cores: 1
rerun-incomplete: true
keep-going: true
